# This file was generated by GoReleaser. DO NOT EDIT.
class Groundcontrol < Formula
  desc ""
  homepage ""
  url "https://github.com/stratumn/groundcontrol/releases/download/v0.7.1/groundcontrol_0.7.1_Darwin_x86_64.tar.gz"
  version "0.7.1"
  sha256 "5601caa5d70e10c7bd87ded1317c62286f9082ac37e42f1bff729a18a301bb13"

  def install
    bin.install "groundcontrol"
  end
end
