# This file was generated by GoReleaser. DO NOT EDIT.
class Groundcontrol < Formula
  desc ""
  homepage ""
  url "https://github.com/stratumn/groundcontrol/releases/download/v0.4.0/groundcontrol_0.4.0_Darwin_x86_64.tar.gz"
  version "0.4.0"
  sha256 "e80c29ae5af99a74be85b085892adfbfd078c50a8152c6c924d3abd824720723"

  def install
    bin.install "groundcontrol"
  end
end
